language: python
python:
 - "3.5"

# command to run tests
script:
 - python -m pytest tests/test_example.py
 - python -m pytest tests/test_fetching.py
 - python -m pytest tests/test_response_parsing.py

 
