dist: jammy
language: python
python:
  - 3.10
cache: pip

before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install --no-root
  - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s
script:
  - just lint
  - just test
