language: python
python:
  - 3.9

addons:
  apt:
    packages:
      - openssl

before_install:
  - pip install poetry
install:
  - poetry install
  - curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s
script:
  - just lint
  - just test
